### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by technomancy** [meric/renderplanet#1]
This is really cool! Any chance you could release this under a free software license? Thanks.

**Comment by meric** [comment]
Done! :)

**Comment by technomancy** [comment]
Lovely; thank you!

I've incorporated it into Bussard here: https://gitlab.com/technomancy/bussard/commit/351d49930cd7ac0ba8a0d05

In the spin effect and the shading being angled by the direction of the star it's orbiting are really nice touches.
